"use client";
import { FormEvent,useState } from "react";
type Employee={id:string;name:string;email:string;role:"ADMIN"|"EMPLOYEE";active:number|boolean};
export function EmployeeManager({initial}:{initial:Employee[]}){
 const[list,setList]=useState(initial);const[name,setName]=useState("");const[email,setEmail]=useState("");const[role,setRole]=useState<"ADMIN"|"EMPLOYEE">("EMPLOYEE");const[message,setMessage]=useState("");
 async function add(e:FormEvent){e.preventDefault();setMessage("");const r=await fetch("/api/employees",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,email,role})});if(!r.ok){setMessage("Não foi possível cadastrar.");return;}const item=await r.json();setList([...list,item]);setName("");setEmail("");}
 async function toggle(item:Employee){const r=await fetch(`/api/employees/${item.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({active:!Boolean(item.active)})});if(r.ok){const updated=await r.json();setList(list.map(x=>x.id===item.id?updated:x));}else setMessage("Não foi possível alterar o acesso.");}
 return <div className="mt-8 grid gap-6"><form onSubmit={add} className="grid gap-3 rounded-2xl bg-white p-5 shadow-sm sm:grid-cols-2"><input className="rounded-lg border p-3" placeholder="Nome" required value={name} onChange={e=>setName(e.target.value)}/><input className="rounded-lg border p-3" type="email" placeholder="E-mail" required value={email} onChange={e=>setEmail(e.target.value)}/><select className="rounded-lg border p-3" value={role} onChange={e=>setRole(e.target.value as typeof role)}><option value="EMPLOYEE">Funcionário</option><option value="ADMIN">Administrador</option></select><button className="rounded-lg bg-slate-900 p-3 font-semibold text-white">Adicionar funcionário</button>{message&&<p className="text-sm text-red-600 sm:col-span-2">{message}</p>}</form><div className="grid gap-3">{list.map(item=><article key={item.id} className="flex flex-col justify-between gap-3 rounded-xl bg-white p-4 shadow-sm sm:flex-row sm:items-center"><div><strong>{item.name}</strong><p className="text-sm text-slate-600">{item.email} · {item.role}</p></div><button onClick={()=>toggle(item)} className="rounded-lg border px-4 py-2 text-sm">{Boolean(item.active)?"Desativar":"Ativar"}</button></article>)}</div></div>;
}
